# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: kyanos-build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
    - name: Build
      run: |
        sudo apt update
        sudo apt install -y git
        sudo apt-get -y install pkg-config
        sudo apt install -y libelf-dev
        
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
        sudo add-apt-repository "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-15 main"
        sudo apt update
        
        sudo apt install -y llvm
        sudo apt install -y clang
        pwd
        ls -l
        make clean && make build-bpf && make

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: kyanos
        path: kyanos
